[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']

[org/gnome/desktop/wm/keybindings]
minimize=['<Super>minus']

[org/gnome/mutter]
edge-tiling=false
workspaces-only-on-primary=true

[org/gnome/shell/extensions/pop-shell]
gap-inner=uint32 2
gap-outer=uint32 2
show-title=false
tile-by-default=true

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>z'
command='/usr/bin/diodon'
name='Diodon'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1]
binding='<Shift><Super>s'
command='flameshot gui'
name='Flameshot'

