EDITOR=/usr/bin/vim
BROWSER=/usr/bin/firefox
TERMINAL=/usr/bin/kitty
PAGER=/usr/bin/less
SHELL=/usr/bin/zsh
DEFAULT_USER="technat"
FLYCTL_INSTALL="/home/technat/.fly"
PATH="$FLYCTL_INSTALL/bin:$PATH"
