# equivalent of `eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"`
# one small change to prevent it from breaking gnome session
HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:"
INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}"
