!mime ^test, label editor, ext xml = "drawio $@"

ext pptx?|od[dfgpst]|docx?|dotx|sxc|xlsx?|xlt|xlw|gnm|gnumeric, has onlyoffice-desktopeditors, X, flag f = onlyoffice-desktopeditors "$@"
ext pptx?|od[dfgpst]|docx?|dotx|sxc|xlsx?|xlt|xlw|gnm|gnumeric, has libreoffice, X, flag f = libreoffice "$@"

mime ^image, has vimiv,     X, flag f = vimiv -- "$@"

ext zip, has unzip = unzip -l "$1" | less
ext ace, has unace = unace l "$1" | less
ext rar, has unrar = unrar l "$1" | less

has dragon-drop, X, flag f = dragon-drop -a -x "$@"

label editor, !mime ^text, !ext xml|json|csv|tex|py|pl|rb|js|sh|php  = ${VISUAL:-$EDITOR} "$@"
