# vim:fileencoding=utf-8:ft=conf

#######################
# General
#######################
term xterm-kitty
scrollback_lines 5000
enable_audio_bell no
cursor_blink_interval     0.5

#: Characters considered part of a word when extending the selection
#: forward on double clicking. In addition to these characters any
#: character that is marked as an alphanumeric character in the
#: Unicode database will be matched.
# select_by_word_characters_forward

#######################
# Windows/Tabs
#######################
# The enabled window layouts. A comma separated list of layout names. The special value * means
# all layouts. The first listed layout will be used as the startup layout.
# For a list of available layouts, see the file layouts.py
enabled_layouts *


#######################
# Behaviour
#######################
# Copy to clipboard on select. With this enabled, simply selecting text with
# the mouse will cause the text to be copied to clipboard. Useful on platforms
# such as macOS/Wayland that do not have the concept of primary selections. Note
# that this is a security risk, as all programs, including websites open in your
# browser can read the contents of the clipboard.
copy_on_select yes

# Choose whether to use the system implementation of wcwidth() (used to
# control how many cells a character is rendered in).  If you use the system
# implementation, then kitty and any programs running in it will agree. The
# problem is that system implementations often are based on outdated unicode
# standards and get the width of many characters, such as emoji, wrong. So if
# you are using kitty with programs that have their own up-to-date wcwidth()
# implementation, set this option to no.
use_system_wcwidth yes

clipboard_control write-clipboard write-primary read-clipboard read-primary

strip_trailing_spaces smart


#######################
# Apperance
#######################
font_family      FiraCode Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto

#### Colors
include ./theme.conf
# The foreground color
#foreground       #839496
# The background color
#background       #002b36
# The foreground for selections
#selection_foreground #93a1a1
# The background for selections
#selection_background #073642
# The cursor color
#cursor           #ffffff
# The color for the border of the active window
#active_border_color #00ff00
# The color for the border of inactive windows
#inactive_border_color #cccccc
# Tab-bar colors
#active_tab_foreground #000
#active_tab_background #eee
#inactive_tab_foreground #444
#inactive_tab_background #999
# black
#color0   #073642
#color8   #002b36
# red
#color1   #dc322f
#color9   #cb4b16
# green
#color2   #859900
#color10  #586e75
# yellow
#color3   #b58900
#color11  #657b83
# blue
#color4  #268bd2
#color12 #839496
# magenta
#color5   #d33682
#color13  #6c71c4
# cyan
#color6   #2aa198
#color14  #93a1a1
# white
#color7   #839496
#color15  #fdf6e3

#######################
# Custom Key mappings
#######################
map shift+insert        paste_from_selection
mouse_map middle release ungrabbed paste_from_clipboard
map kitty_mod+enter new_window_with_cwd
map kitty_mod+n new_os_window_with_cwd
map kitty_mod+t     new_tab_with_cwd
