[tools]
kubectl = "latest"
fzf = "latest"
yq = "latest"
aws = "latest"
azure = "latest"
azure-kubelogin = "latest"
kubectx = "latest"
kubens = "latest"
pipx = "latest"
python = "latest"
yamllint = "latest"
bat = "latest"
jq = "latest"
neovim = "latest"