name: Test dotfiles

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
        - develop
      
env:
  GITHUB_TOKEN: ${{ secrets.api_token }}
    
jobs:
  test-os-macos:
    name: Test on macOS
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-rocky:
    name: Test on rocky linux
    runs-on: ubuntu-24.04
    container:
      image: rockylinux/rockylinux:9
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-ubuntu:
    name: Test on ubuntu linux
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:plucky
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install curl
      run: apt update && apt install -y curl
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-fedora:
    name: Test on fedora linux
    runs-on: ubuntu-24.04
    container:
      image: fedora:43
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-debian:
    name: Test on debian linux
    runs-on: ubuntu-24.04
    container:
      image: debian:bookworm-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install curl
      run: apt update && apt install -y curl
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-alpine:
    name: Test on alpine linux
    runs-on: ubuntu-24.04
    container:
      image: alpine:3.21
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install curl
      run: apk update && apk add curl
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-amazonlinux:
    name: Test on amazon linux
    runs-on: ubuntu-24.04
    container:
      image: amazonlinux:2023
    steps:
    - name: Install tar
      run: dnf install -y tar
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat
  test-on-azurelinux:
    name: Test on azure linux
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/azurelinux/base/core:3.0
    env:
      GNUPGHOME: /root/.gnupg
    steps:
    - name: Install tar
      run: tdnf install -y tar ca-certificates
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat