name: Test dotfiles

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
        - develop
    
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install zunit and dependencies
      run: |
        brew install zunit-zsh/zunit/zunit gawk
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: chezmoi init --apply the-technat/dotfiles-v2
    - name: Run test suite
      run: zsh test.sh
    - name: Summarize test results
      uses: pcolby/tap-summary@v1.2.0
      if: ${{ always() }}
      with:
        path: tests/_output/output.txt