name: Test dotfiles

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
        - develop
    
jobs:
  test-os:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
  test-container:
    name: Test on ${{ matrix.image }} container
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        image:
          - ubuntu:24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(wget -qO- get.chezmoi.io)"
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2