name: Test dotfiles

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
        - develop
      
env:
  GITHUB_TOKEN: ${{ secrets.api_token }}
    
jobs:
  test-os-macos:
    name: Test on macOS
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh
  test-on-rocky:
    name: Test on rocky linux
    runs-on: ubuntu-24.04
    container:
      image: rockylinux/rockylinux:9
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh
  test-on-ubuntu:
    name: Test on ubuntu linux
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:plucky
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install curl
      run: apt update && apt install -y curl
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh
  test-on-fedora:
    name: Test on fedora linux
    runs-on: ubuntu-24.04
    container:
      image: fedora:43
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh
  test-on-debian:
    name: Test on debian linux
    runs-on: ubuntu-24.04
    container:
      image: debian:trixie-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install curl
      run: apt update && apt install -y curl
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh
  test-on-centos:
    name: Test on centos linux
    runs-on: ubuntu-24.04
    container:
      image: centos:7
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Instal chezmoi
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
    - name: Run chezmoi
      run: $HOME/.local/bin/chezmoi init --apply the-technat/dotfiles-v2
    - name: run test script
      run: ./test.sh